model:
    loc: '../../../files/data/training_sets/'
    file: 'training_set_v1_6.csv'
    #file: "thailand_dataset_v1_1.csv"
meta:
    experiment_name: "/Threshold changes/Brazil/v128"
    run_name: "XGBoost with a . 5 threshold"
    target: ['A4A_right']
    predictors: ['avg_d_kbps',
       'avg_u_kbps',
       'mean_GHM', 'avg_rad_mean',  'cf_cvg_mean',  'viirs_slope_yr',
       'cf_cvg_viirs_slope_yr', 'viirs_slope_month',
       'viirs_slope_month_cf_cvg', 'estimate_mau', 'pop_norm']
parameter:
    test_size: .3
    inner_cv: 10
    iterations: 3
    threshold: .3
    Random_Forest:
        n_estimators: [4, 5, 6, 15]
        max_depth: [5, 10, 15, 20]
    lightgbm:
        boosting_type: ['dart']
        max_depth: [-1, 5, 10, 20]
        learning_rate: [0.01, 0.05, 0.1, 0.2]
        n_estimators: [50, 100, 200, 500]
    XGBoost:
          max_depth: [9, 12]
          eta: [ 0.15, 0.2]
          n_estimators: [350, 550]
